# Generated by Django 5.2.8 on 2025-12-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains_roads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountainroute',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='routes/', verbose_name='Основне фото'),
        ),
    ]
